### ISSUE TITLE
Entry "view live information" is missing from context menu of app node

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-azurespringcloud#54]
With SpringBootDashboard extension installed, the entry is still not there.
Is there any change to the contextValue of the node?

https://github.com/microsoft/vscode-azurespringcloud/blob/7c472b902787d741eb204dd4421ae738dab275fb/package.json#L341-L344

**Comment by wangmingliang-ms** [comment]
@Eskibear  sorry, the initialization entry was removed by mistake when integrating with Azure Resources extension.

**Comment by Eskibear** [comment]
Thanks for the quick fix!
